# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jun 12 16:15:39 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(437, 205)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.l_avail = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(24)
        self.l_avail.setFont(font)
        self.l_avail.setAlignment(QtCore.Qt.AlignCenter)
        self.l_avail.setObjectName("l_avail")
        self.gridLayout.addWidget(self.l_avail, 0, 0, 1, 5)
        self.l_last = QtWidgets.QLabel(self.centralwidget)
        self.l_last.setAlignment(QtCore.Qt.AlignCenter)
        self.l_last.setObjectName("l_last")
        self.gridLayout.addWidget(self.l_last, 3, 0, 1, 5)
        self.l_solved_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_solved_1.setObjectName("l_solved_1")
        self.gridLayout.addWidget(self.l_solved_1, 4, 0, 1, 1)
        self.l_solved_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_solved_2.setObjectName("l_solved_2")
        self.gridLayout.addWidget(self.l_solved_2, 4, 1, 1, 1)
        self.l_solved_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_solved_3.setObjectName("l_solved_3")
        self.gridLayout.addWidget(self.l_solved_3, 4, 2, 1, 1)
        self.l_solved_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_solved_4.setObjectName("l_solved_4")
        self.gridLayout.addWidget(self.l_solved_4, 4, 3, 1, 1)
        self.l_solved_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_solved_5.setObjectName("l_solved_5")
        self.gridLayout.addWidget(self.l_solved_5, 4, 4, 1, 1)
        self.l_typed = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(24)
        self.l_typed.setFont(font)
        self.l_typed.setAlignment(QtCore.Qt.AlignCenter)
        self.l_typed.setObjectName("l_typed")
        self.gridLayout.addWidget(self.l_typed, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 437, 25))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(self.menubar)
        self.menuGame.setObjectName("menuGame")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSolve = QtWidgets.QAction(MainWindow)
        self.actionSolve.setObjectName("actionSolve")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionWordlists = QtWidgets.QAction(MainWindow)
        self.actionWordlists.setObjectName("actionWordlists")
        self.menuGame.addAction(self.actionNew)
        self.menuGame.addAction(self.actionSolve)
        self.menuGame.addSeparator()
        self.menuGame.addAction(self.actionWordlists)
        self.menuGame.addSeparator()
        self.menuGame.addAction(self.actionQuit)
        self.menuGame.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuGame.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Pynagram", None))
        self.l_avail.setText(QtWidgets.QApplication.translate("MainWindow", "ABCDEFG", None))
        self.l_last.setText(QtWidgets.QApplication.translate("MainWindow", "Last Word:", None))
        self.l_solved_1.setText(QtWidgets.QApplication.translate("MainWindow", "Something", None))
        self.l_solved_2.setText(QtWidgets.QApplication.translate("MainWindow", "Something", None))
        self.l_solved_3.setText(QtWidgets.QApplication.translate("MainWindow", "Something", None))
        self.l_solved_4.setText(QtWidgets.QApplication.translate("MainWindow", "Something", None))
        self.l_solved_5.setText(QtWidgets.QApplication.translate("MainWindow", "Something", None))
        self.l_typed.setText(QtWidgets.QApplication.translate("MainWindow", "TUVWXYZ", None))
        self.menuGame.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Game", None))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Help", None))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New", None))
        self.actionNew.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None))
        self.actionSolve.setText(QtWidgets.QApplication.translate("MainWindow", "Solve", None))
        self.actionSolve.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+L", None))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None))
        self.actionWordlists.setText(QtWidgets.QApplication.translate("MainWindow", "Word Lists", None))
        self.actionWordlists.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None))

